spring:
  application:
    name: studymate

  datasource:
    url: jdbc:postgresql://localhost:5435/studymate
    username: studymate
    password: ${POSTGRES_PASSWORD}

  jpa:
      hibernate:
        ddl-auto: update

jwt:
  secret: your-secret-key-must-be-long-enough
  access-token-expiration-seconds: 3600
