package com.studymate.global.domain;

public enum ActivityRegion {
    SEOUL_GANGNAM,
    SEOUL_GANGDONG,
    SEOUL_GANGBUK,
    SEOUL_GANGSEO,
    SEOUL_GWANAK,
    SEOUL_GWANGJIN,
    SEOUL_GURO,
    SEOUL_GEUMCHEON,
    SEOUL_NOWON,
    SEOUL_DOBONG,
    SEOUL_DONGDAEMUN,
    SEOUL_DONGJAK,
    SEOUL_MAPO,
    SEOUL_SEODAEMUN,
    SEOUL_SEOCHO,
    SEOUL_SEONGDONG,
    SEOUL_SEONGBUK,
    SEOUL_SONGPA,
    SEOUL_YANGCHEON,
    SEOUL_YEONGDEUNGPO,
    SEOUL_YONGSAN,
    SEOUL_EUNPYEONG,
    SEOUL_JONGNO,
    SEOUL_JUNG,
    SEOUL_JUNGNANG
}
